import {Component, EventEmitter, Output, OnInit} from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  template: `
      <h2>
          <!-- <p> {{ title }} </p> -->
          <input class="todo-input"
                 #inputElementRef
                 [value] = "title" (keyup.enter) = "submitValue($event.target.value)">
          <button class="btn"
                  (click)="submitValue(inputElementRef.value)">
              Save
          </button>
      </h2>
  `,
  styleUrls: ['./input-button-unit.component.css']
})
export class InputButtonUnitComponent implements OnInit {
  @Output() submit: EventEmitter<string> = new EventEmitter();
  title = 'Hello world!';

  constructor() {
  }

  ngOnInit() {

  }

  submitValue(newTitle: string) {
    this.submit.emit(newTitle);
  }

/*  generateTitle(): string {
    return 'This title was generated by a method';
  }*/

}
